language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
after_failure:
 - cat build/reports/*/*.xml
cache:
 directories:
  - $HOME/.m2
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches
notifications:
  slack: tecnicas7510-02-2016:AZCMT2ejqt8dha4SQoC3PYK8
